const ffmpegFilters = [
    "Bassboost",
    "Bassboost_low",
    "Chorus",
    "Dim",
    "Earrape",
    "Fadein",
    "Flanger",
    "Gate",
    "Haas",
    "Karaoke",
    "Lofi",
    "Mcompand",
    "Mono",
    "Nightcore",
    "Normalizer",
    "Phaser",
    "Pulsator",
    "Reverse",
    "Softlimiter",
    "Subboost",
    "Surrounding",
    "Treble",
    "Tremolo",
    "Vaporwave",
    "Vibrato",
];

module.exports = ffmpegFilters;